language: node_js
env: IN_TRAVIS=true
node_js:
- '0.10'
notifications:
  email:
    recipients:
    - opensoc-github@external.cisco.com
    on_success: never
    on_failure: always
before_script:
  - sudo apt-get install -y libpcap-dev tshark
  - sudo npm install -g grunt-cli
