language: node_js
env: IN_TRAVIS=true
node_js:
- '0.10'

branches:
	only:
		- master
		- kibana4

before_install:
    - sudo apt-get install -y libpcap-dev tshark
    - npm install -g grunt-cli
install: cd kibana && npm install && cd .. && npm install
notifications:
  email:
    recipients:
    - opensoc-github@external.cisco.com
    on_success: never
    on_failure: always
