language: node_js
env: IN_TRAVIS=true
node_js:
- '0.10'
notifications:
  email:
    recipients:
    - opensoc-github@external.cisco.com
    on_success: never
    on_failure: always
  hipchat:
    rooms:
      secure: R8B4ZKfk8olu5Kvu/bOPqQzP5O6T2LXqW+rIVxbPPs5FEGYexo/ItUlGYA3eLF3dTrvNYYmSVINsvm7TQyvqeexLL7KxGalzeboheTpg1f1+RRkzNa8F5J/1X+lSJhp4hDqXF2uzyVaq2V4lfULJIEolYQf3haKztkjyplF1yHw=
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database opensoc_test;' -U postgres
- script/migrate up -e ci
