language: node_js

env: IN_TRAVIS=true
node_js:
- '0.10'

branches:
  only:
    - master
    - kibana4

before_install:
    - sudo apt-get install -y libpcap-dev tshark
    - npm install -g grunt-cli
install: cd kibana && npm install && cd .. && npm install
notifications:
  email:
    recipients:
    - opensoc-github@external.cisco.com
    on_success: never
    on_failure: always

node_js:
- '0.10'
install:
- npm install -g grunt-cli bower
- npm install
- bower install
script:
- npm test
notifications:
  email:
  - rashid.khan@elastic.co
  - spencer.alger@elastic.co
  hipchat:
    rooms:
      secure: UKrVR+5KztHarodQruQe97UJfwftutD6RNdXlVkr+oIr2GqccisDIIN9pAzS/kxl+eAnP1uT6VHzc9YI/jgbrmiSkz3DHViw+MwDwY2aIDgI8aHEbd/4B2ihtb15+OYTVbb+lytyz4+W8A8hSmbkTR/P/uFIJ+EYcBeYZfw1elo=
    format: html
    on_success: change
    template:
    - ! '%{repository_slug}/%{branch} by %{author}: %{commit_message} (<a href="%{build_url}">open</a>)'

